config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'

  # sessionsコントローラ
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # roomsコントローラ
  get '/home', to: 'rooms#home'
  get '/top', to: 'rooms#top'
  post 'reservations/confirm', to: 'reservations#confirm'

  resources :rooms do
    post '/searches', to: 'searches#search'
  end

  resources :users
  resources :reservations

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :reservation
  has_one_attached :image
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  # バリデーション
  validates :start, presence: true
  validates :end, presence: true
  validates :number_of_people, presence: true
  validates :room_id, presence: true

  validate :start_finish_check
  validate :strat_check

  # カスタムバリデーションの定義
  def start_finish_check
    errors.add(:end, "は開始時刻より遅い時間を選択してください") if self.start > self.end
  end

  def strat_check
    errors.add(:start, "現在の時刻より遅い時間を選択してください") if self.start < Time.now
  end

  # リレーション
  belongs_to :user
  belongs_to :room
  
end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :reservation
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true

  has_one_attached :image
  has_many :rooms
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations
  end

  def new
    @reservation = Reservation.new
    @room = Room.find(params[:id])
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(reservation_params[:room_id])
    
    # confirmアクション実行時にバリデーションチェックを実行したい
    # if @reservation.errors.full_messages.present?
    #   flash[:error] = @reservation.errors.full_messages
    #   redirect_to new_reservation_path(id: @room.id), flash: { error: @reservation.errors.full_messages }
    # end
  end

  def create
    @reservation = Reservation.new(reservation_params.merge(user_id: current_user.id))
    # binding.pry
    @room = Room.find(reservation_params[:room_id])
    if @reservation.save
      flash[:notice] = "ルームを予約しました"
      redirect_to rooms_path
    else
      redirect_to new_reservation_path(id: @room.id), flash: { error: @reservation.errors.full_messages }
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = '予約をキャンセルしました'
    redirect_to :reservations
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start, :end, :number_of_people, :room_id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def top
    @q = Room.ransack(params[:q])
    @rooms = @q.result
    @rooms = Room.all
  end

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result
    @count = @rooms.count
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params.merge(user_id: current_user.id))
    if @room.save
      flash[:notice] = "ルームを登録しました"
      redirect_to :rooms
    end
  end

  def show
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = 'ルームを削除しました'
    redirect_to :rooms
  end

  def home
    @rooms = current_user.rooms
  end

  def search
    
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :room_introduction, :usage_fee, :address, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def login
    @user = User.new
  end
  
  def create
    @user = User.find_by(email: session_params[:email])
  
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'ログインしました。'    
    else
      flash[:notice] = "メールアドレスまたはパスワードが違います"
      render :login
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'ログアウトしました'
  end


  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "アカウントを登録しました"
      redirect_to :rooms
    else
      render :new
    end
  end

  # ログイン機能実装後に実装（セッションにidを持たせるため）
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_edit_params)
      flash[:notice] = 'アカウントを更新しました'
      redirect_to user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました'
    redirect_to :users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_edit_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSharingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/sanitize.css" rel="stylesheet"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class='left-header'>
        <div><%= link_to 'Room Share', top_path, class: 'app-title' %></div>
      </div>
      <div class='right-header'>
        <% if current_user %>
          <span class='name'><%= current_user.name %></span>
          <% if current_user.image.attached? %>
            <%= image_tag current_user.image, id: 'user-icon' %>
          <% else %>
            <%= image_tag 'user-icon.png', id: 'user-icon' %>
          <% end %>
        <% else %>
          <%= link_to 'ログイン', :login, class: 'login-button' %>
          <%= link_to '登録する', :new_user, class: 'signup-button' %>
        <% end %>
      </div>
    </header>
    <% if current_user %>
      <nav id='navigasion-box'>
        <ul>
            <li><%= link_to 'ルーム登録', new_room_path, class: 'setting-menu' %></li>
            <li><%= link_to '予約済みルーム一覧', reservations_path, class: 'setting-menu' %></li>
            <li><%= link_to '登録済みルーム一覧', 'home', class: 'setting-menu' %></li>
            <li><%= link_to 'アカウント設定', edit_user_path(current_user.id), class: 'setting-menu' %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete, class: 'setting-menu' %></li>
        </ul>
      </nav>
    <% end %>

    <%= yield %>

    <footer>
      <div>&copy; 2022 RoomShare.INC</div>
    </footer>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :room_name, 'ルーム名', required: true %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :room_name, class: 'text-form', placeholder: 'ルーム名を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :room_introduction, 'ルーム紹介' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :room_introduction, class: 'text-form', placeholder: 'ルーム説明を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :usage_fee, '料金' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :usage_fee, class: 'text-form', placeholder: '一日当あたりの料金を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :address, '住所' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :address, class: 'text-form', placeholder: '住所を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :image, 'ルーム画像' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.file_field :image, required: true %>
    </div>
  </div>
  <div class='form-bottun'>
    <%= f.submit '登録', class: 'submit-button' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'posts_new' %>

<div class='main-container'>
  <p class='page-title'>ルーム情報登録</p>

  <%# _form.html.erbを表示 %>
  <%= render 'form', post: @post %>

</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts_index' %>


<div class='main-container'>

  <div class='search-box'>
    <div class='search-form'>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :address_cont, placeholder: 'エリア', class: 'form' %>
        <%= f.search_field :room_name_cont, placeholder: 'フリーワード', class: 'form' %>
        <%= f.submit "検索", class: 'search-button' %>
      <% end %>
    </div>
  </div>

  <p class='result-text'><%= @count %>件が見つかりました</p>
  
  <div class='content'>
    <% @posts.each do |post| %>
      <div class='card-box'>
        <%= link_to(new_reservation_path(id: post.id)) do%>
          <p><%= image_tag(post.image.variant(resize: 399)) if post.image.attached? %></p>
          <p class='room-name'><%= post.room_name %></p>
          <p class='room-address'><%= post.address %></p>
          <p class='usage-fee'>1人 ¥<%= post.usage_fee %> /日</p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'posts_new' %>

<div class='main-container'>
  <p class='page-title'>ルーム情報登録</p>

  <%# _form.html.erbを表示 %>
  <%= render 'form', post: @post %>

</div>

app/views/posts/top.html.erb
<%= stylesheet_link_tag 'posts_top' %>

<div class='main-container'>

  <h1>
    Room Sahreで<br>
    まだ体験したことのない<br>
    旅をしよう 
  </h1>

  <div class='search-form'>
    <%= search_form_for @q do |f| %>
      <div class='form-box'>
        <%= f.search_field :address_cont, placeholder: 'エリア名を入力', class: 'input-form' %>
      </div>
      <div class='form-box'>
        <%= f.submit "検索", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>


<div class='sub-container'>
  <h2>おすすめエリア</h2>

  <div class='search'>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '東京' %>
      <%= f.submit "東京", class: 'search-box tokyo' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '大阪' %>
      <%= f.submit "大阪", class: 'search-box osaka' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '京都' %>
      <%= f.submit "京都", class: 'search-box kyoto' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '札幌' %>
      <%= f.submit "札幌", class: 'search-box sapporo' %>
    <% end %>
  </div>
</div>

app/views/reservations/confirm.html.erb
<%= stylesheet_link_tag 'reservations_confirm' %>

<% if flash[:error].present? %>
  <% flash[:error].each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class='main-container'>

  <div class='page-title'>この部屋を予約する</div>

  <div class='reservation-box'>
    <p><%= image_tag(@room.image.variant(resize: 720)) if @room.image.attached? %></p>
    <div class='room-info-box'>
      <p class='room-name'><%= @room.room_name %></p>
      <p class='room-address'><%= @room.address %></p>
      <p class='room-introduction'><%= @room.room_introduction %></p>
    </div>

    <div class='reservation-info-box'>
      <%= form_with model: @reservation do |f| %>
        
        <table>
          <tr>
            <th><%= f.label :starg, '開始日' %></th>
            <td><%= f.date_field :start, readonly: true, class: 'text-form' %></td>
          </tr>
          <tr>
            <th><%= f.label :end, '終了日' %></th>
            <td><%= f.date_field :end, readonly: true, class: 'text-form' %></td>
          </tr>
          <tr>
            <th><%= f.label :number_of_people, '人数' %></th> 
            <td><%= f.text_field :number_of_people, readonly: true, class: 'text-form' %></td>
          </tr>
          <tr>
            <th>合計料金</th> 
            <td>¥ <%= ((@reservation.number_of_people * @room.usage_fee) * ((@reservation.end-@reservation.start)/86400).to_i).to_s(:delimited) %></td>
          </tr>
        </table>

        <%= f.hidden_field :room_id, :value => @room.id %>
        <%= f.submit '予約を確定する', class: 'submit-button' %>

      <% end %>
      <%= link_to '戻る', rooms_path, class: 'back-button' %>
    </div>

  </div>
</div>

app/views/reservations/index.html.erb
<%= stylesheet_link_tag 'reservations_index' %>

<div class='main-container'>
  <div class='page-title'>予約済みルーム一覧</div>
  <table>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th class='th-introduction'>宿泊人数</th>
      <th>合計料金</th>
      <th class='th-image'>チェックイン</th>
      <th class='th-name'>チェックアウト</th>
      <th class='th-created-at'>予約日</th>
      <th class='th-delete'>キャンセル</th>
    </tr>

    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= image_tag(reservation.room.image.variant(resize: '500x100')) %></td>
        <td><%= reservation.room.room_name %></td>
        <td><%= reservation.room.room_introduction %></td>
        <td><%= reservation.number_of_people %></td>
        <td>¥ <%= ((reservation.number_of_people * reservation.room.usage_fee) * ((reservation.end-reservation.start)/86400).to_i).to_s(:delimited) %></td>
        <td><%= reservation.start.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.end.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to 'キャンセル', reservation, method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/reservations/new.html.erb
<%= stylesheet_link_tag 'reservations_new' %>

<% if flash[:error].present? %>
  <% flash[:error].each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class='main-container'>
  <div class='page-title'>この部屋を予約する</div>
  <div class='reservation-box'>
    <div class='left-box'>
      <p><%= image_tag(@room.image.variant(resize: 720)) if @room.image.attached? %></p>
      <p class='room-name'><%= @room.room_name %></p>
      <p class='room-address'><%= @room.address %></p>
      <p class='room-introduction'><%= @room.room_introduction %></p>
    </div>

    <div class='right-box'>
      <p class='usage-fee'>1人 ¥<%= @room.usage_fee %> /日</p>
      <%= form_with(model: @reservation, url: reservations_confirm_path(@reservation)) do |f| %>
        <div class='form-content'>
          <div class='label-box'>
            <%= f.label :starg, '開始日' %>
            <a class='required-text'>必須</a>
          </div>
          <div class='text-box'>
            <%= f.date_field :start, class: 'text-form' %>
          </div>
        </div>
        <div class='form-content'>
          <div class='label-box'>
            <%= f.label :end, '終了日' %>
            <a class='required-text'>必須</a>
          </div>
          <div class='text-box'>
            <%= f.date_field :end, class: 'text-form' %>
          </div>
        </div>
        <div class='form-content'>
          <div class='label-box'>
            <%= f.label :number_of_people, '人数' %>
            <a class='required-text'>必須</a>
          </div>
          <div class='text-box'>
            <%= f.text_field :number_of_people, class: 'text-form' %>
          </div>
        </div>
        <div class='form-bottun'>
          <%= f.submit '予約する', class: 'submit-button' %>
        </div>
        <%= f.hidden_field :room_id, :value => @room.id %>
      <% end %>

      <div class='login-page'>
        <%= link_to '戻る', rooms_path, class: 'login-page-button' %>
      </div>
    </div>

  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_with model: room do |f| %>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :room_name, 'ルーム名', required: true %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :room_name, class: 'text-form', placeholder: 'ルーム名を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :room_introduction, 'ルーム紹介' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :room_introduction, class: 'text-form', placeholder: 'ルーム説明を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :usage_fee, '料金' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :usage_fee, class: 'text-form', placeholder: '一日当あたりの料金を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :address, '住所' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :address, class: 'text-form', placeholder: '住所を入力', required: true %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :image, 'ルーム画像' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.file_field :image, required: true %>
    </div>
  </div>
  <div class='form-bottun'>
    <%= f.submit '登録', class: 'submit-button' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%= stylesheet_link_tag 'rooms_new' %>

<div class='main-container'>
  <p class='page-title'>ルーム情報登録</p>

  <%# _form.html.erbを表示 %>
  <%= render 'form', room: @room %>

</div>

app/views/rooms/home.html.erb
<%= stylesheet_link_tag 'rooms_home' %>

<div class='main-container'>
  <div class='page-title'>登録済みルーム一覧</div>
  <table>
    <tr>      
      <th class='th-image'>ルーム画像</th>
      <th class='th-name'>ルーム名</th>
      <th class='th-introduction'>ルーム紹介</th>
      <th class='th-fee'>利用料金</th>
      <th class='th-adress'>住所</th>
      <th class='th-created_time'>登録日</th>
      <th class='th-delete'>削除</th>
    </tr>

    <% @rooms.each do |room| %>
      <%= link_to edit_room_path(room) do%>
        <tr>
          <td><%= image_tag(room.image.variant(resize: '500x100')) if room.image.attached? %></td>
          <td><%= room.room_name %></td>
          <td><%= room.room_introduction %></td>
          <td>¥<%= room.usage_fee.to_s(:delimited) %></td>
          <td><%= room.address %></td>
          <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= link_to '削除', room, method: :delete %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/rooms/index.html.erb
<%= stylesheet_link_tag 'rooms_index' %>


<div class='main-container'>

  <div class='search-box'>
    <div class='search-form'>
      <%= search_form_for @q do |f| %>
        <%= f.search_field :address_cont, placeholder: 'エリア', class: 'form' %>
        <%= f.search_field :room_name_cont, placeholder: 'フリーワード', class: 'form' %>
        <%= f.submit "検索", class: 'search-button' %>
      <% end %>
    </div>
  </div>

  <p class='result-text'><%= @count %>件が見つかりました</p>
  
  <div class='content'>
    <% @rooms.each do |room| %>
      <div class='card-box'>
        <%= link_to(new_reservation_path(id: room.id)) do%>
          <p><%= image_tag(room.image.variant(resize: 399)) if room.image.attached? %></p>
          <p class='room-name'><%= room.room_name %></p>
          <p class='room-address'><%= room.address %></p>
          <p class='usage-fee'>1人 ¥<%= room.usage_fee %> /日</p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/rooms/new.html.erb
<%= stylesheet_link_tag 'rooms_new' %>

<div class='main-container'>
  <p class='page-title'>ルーム情報登録</p>

  <%# _form.html.erbを表示 %>
  <%= render 'form', room: @room %>

</div>

app/views/rooms/reservation.html.erb
<%= stylesheet_link_tag 'reservations_new' %>

<div class='main-container'>
  <div class='page-title'>この部屋を予約する</div>

    <%= form_with model: @reservation do |f| %>
      <div class='form-content'>
        <div class='label-box'>
          <%= f.label :starg, 'チェックイン' %>
          <a class='required-text'>必須</a>
        </div>
        <div class='text-box'>
          <%= f.date_field :start, class: 'text-form' %>
        </div>
      </div>
      <div class='form-content'>
        <div class='label-box'>
          <%= f.label :end, 'チェックアウト' %>
          <a class='required-text'>必須</a>
        </div>
        <div class='text-box'>
          <%= f.date_field :end, class: 'text-form' %>
        </div>
      </div>
      <div class='form-content'>
        <div class='label-box'>
          <%= f.label :number_of_people, '宿泊人数' %>
          <a class='required-text'>必須</a>
        </div>
        <div class='text-box'>
          <%= f.text_field :number_of_people, class: 'text-form' %>
        </div>
      </div>
      <div class='form-bottun'>
        <%= f.submit '予約する', class: 'submit-button' %>
      </div>
    <% end %>

    <div class='login-page'>
      <%= link_to '戻る', :home, class: 'login-page-button' %>
    </div>


  </div>
<div>

app/views/rooms/top.html.erb
<%= stylesheet_link_tag 'rooms_top' %>

<div class='main-container'>

  <h1>
    Room Sahreで<br>
    まだ体験したことのない<br>
    旅をしよう 
  </h1>

  <div class='search-form'>
    <%= search_form_for @q do |f| %>
      <div class='form-box'>
        <%= f.search_field :address_cont, placeholder: 'エリア名を入力', class: 'input-form' %>
      </div>
      <div class='form-box'>
        <%= f.submit "検索", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>


<div class='sub-container'>
  <h2>おすすめエリア</h2>

  <div class='search'>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '東京' %>
      <%= f.submit "東京", class: 'search-box tokyo' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '大阪' %>
      <%= f.submit "大阪", class: 'search-box osaka' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '京都' %>
      <%= f.submit "京都", class: 'search-box kyoto' %>
    <% end %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :address_cont, :value => '札幌' %>
      <%= f.submit "札幌", class: 'search-box sapporo' %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: user do |f| %>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :name, 'ユーザー名' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :name, class: 'text-form' , placeholder: 'ユーザー名を入力' %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :email, 'メールアドレス' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.text_field :email, class: 'text-form', placeholder: 'メールアドレスを入力' %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :password, 'パスワード' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.password_field :password, class: 'text-form', placeholder: 'パスワードを入力' %>
    </div>
  </div>
  <div class='form-content'>
    <div class='label-box'>
      <%= f.label :password_digest, 'パスワード（確認）' %>
      <a class='required-text'>必須</a>
    </div>
    <div class='text-box'>
      <%= f.password_field :password_confirmation, class: 'text-form', placeholder: 'パスワード（確認）を入力' %>
    </div>
  </div>
  <div class='form-bottun'>
    <%= f.submit 'アカウント登録', class: 'submit-button' %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users_index' %> 


<div class='main-container'>
  <div class='page-title'>ユーザー一覧</div>
  <table>
    <tr>
      <th class='account-name'>Id</th>
      <th class='account-name'>アカウント名</th>
      <th class='email'>メールアドレス</th>
      <th class='icon-img'>アイコン画像</th>
      <th class='introduction'>自己紹介</th>
      <th>編集</th>
      <th>削除</th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email%></td>
        <td><%= image_tag(user.image.variant(resize: '500x100')) if user.image.attached? %></td>
        <td><%= user.introduction %></td>
        <td><%= link_to '確認', user_path(user) %></td> 
        <td><%= link_to '編集', edit_user_path(user) %></td> 
        <td><%= link_to '削除', user, method: :delete, data: {confirm: "本当に削除しますか？"} %></td> 
      </tr>
    <% end %>
  </table>
</div>